import { describe, expect, it } from 'vitest';
import {
  MAX_MESSAGE_BYTES, decodeClientMessage, decodeServerMessage, decodeServerMessageResult, encodeClientMessage,
  encodeServerMessage, type ClientMessage,
} from '../src/net/protocol';

/** Generated by the real Swift encoder (CasinoNet WireCodec, Swift 6.0.3) – do not edit by hand. */
const SWIFT_SAMPLES: Record<string, string> = {
  "c.hello": "{\"hello\":{\"_0\":{\"protocolVersion\":1,\"displayName\":\"Kim\"}}}",
  "c.helloToken": "{\"hello\":{\"_0\":{\"protocolVersion\":1,\"token\":\"tok\",\"displayName\":\"Kim\"}}}",
  "c.rename": "{\"rename\":{\"displayName\":\"Neu\"}}",
  "c.addFriend": "{\"addFriend\":{\"friendCode\":\"ABC234\"}}",
  "c.removeFriend": "{\"removeFriend\":{\"playerID\":\"P2\"}}",
  "c.createRoom": "{\"createRoom\":{\"game\":\"poker\"}}",
  "c.joinRoom": "{\"joinRoom\":{\"code\":\"ABCDEF\"}}",
  "c.setRoomGame": "{\"setRoomGame\":{\"game\":\"blackjack\"}}",
  "c.startRoom": "{\"startRoom\":{}}",
  "c.leaveRoom": "{\"leaveRoom\":{}}",
  "c.inviteFriend": "{\"inviteFriend\":{\"playerID\":\"P2\"}}",
  "c.findMatch": "{\"findMatch\":{\"game\":\"blackjack\"}}",
  "c.matchWithBots": "{\"matchWithBots\":{}}",
  "c.keepWaiting": "{\"keepWaiting\":{}}",
  "c.cancelMatch": "{\"cancelMatch\":{}}",
  "c.actBet": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"placeBet\":{\"amount\":50}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.actBJ": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"blackjack\":{\"action\":\"double\"}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.actRaise": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"poker\":{\"action\":{\"raise\":{\"to\":40}}}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.actFold": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"poker\":{\"action\":{\"fold\":{}}}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.actAllIn": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"poker\":{\"action\":{\"allIn\":{}}}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.actRebuy": "{\"tableAction\":{\"_0\":{\"stateVersion\":7,\"action\":{\"rebuy\":{}},\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "c.leaveTable": "{\"leaveTable\":{}}",
  "c.claimOnlineRescue": "{\"claimOnlineRescue\":{}}",
  "c.ping": "{\"ping\":{}}",
  "s.welcome": "{\"welcome\":{\"_0\":{\"player\":{\"id\":\"P1\",\"friendCode\":\"ABC234\",\"displayName\":\"Kim\"},\"onlineChips\":5000,\"token\":\"secret\"}}}",
  "s.account": "{\"account\":{\"_0\":{\"player\":{\"id\":\"P1\",\"displayName\":\"Kim\",\"friendCode\":\"ABC234\"},\"onlineChips\":4900}}}",
  "s.friends": "{\"friends\":{\"_0\":[{\"player\":{\"id\":\"P2\",\"friendCode\":\"XYZ789\",\"displayName\":\"Lea\"},\"presence\":\"inGame\"}]}}",
  "s.friendsEmpty": "{\"friends\":{\"_0\":[]}}",
  "s.room": "{\"room\":{\"_0\":{\"code\":\"ABCDEF\",\"members\":[{\"id\":\"P1\",\"displayName\":\"Kim\",\"friendCode\":\"ABC234\"},{\"id\":\"P2\",\"friendCode\":\"XYZ789\",\"displayName\":\"Lea\"}],\"status\":\"waiting\",\"hostID\":\"P1\",\"game\":\"poker\"}}}",
  "s.roomNil": "{\"room\":{}}",
  "s.invitation": "{\"invitation\":{\"_0\":{\"game\":\"blackjack\",\"roomCode\":\"ABCDEF\",\"from\":{\"id\":\"P2\",\"displayName\":\"Lea\",\"friendCode\":\"XYZ789\"}}}}",
  "s.mmSearching": "{\"matchmaking\":{\"_0\":{\"searching\":{\"game\":\"poker\",\"since\":1700000000123}}}}",
  "s.mmNoMatch": "{\"matchmaking\":{\"_0\":{\"noMatchFound\":{\"game\":\"blackjack\"}}}}",
  "s.mmMatched": "{\"matchmaking\":{\"_0\":{\"matched\":{\"tableID\":\"T1\"}}}}",
  "s.mmIdle": "{\"matchmaking\":{\"_0\":{\"idle\":{}}}}",
  "s.tableBJ": "{\"table\":{\"_0\":{\"tableID\":\"T1\",\"yourSeatID\":0,\"seats\":[{\"isBot\":false,\"isConnected\":true,\"seatID\":0,\"player\":{\"id\":\"P1\",\"friendCode\":\"ABC234\",\"displayName\":\"Kim\"}},{\"seatID\":1,\"isConnected\":true,\"isBot\":true,\"player\":{\"id\":\"bot-1\",\"displayName\":\"Bot Ava\",\"friendCode\":\"\"},\"botStyle\":\"shark\"}],\"turnDeadline\":1700000025500,\"blackjack\":{\"bettingOpen\":false,\"seats\":[{\"seatID\":0,\"hands\":[{\"id\":1,\"bet\":50,\"result\":{\"payout\":125,\"handID\":1,\"stake\":50,\"outcome\":\"blackjack\"},\"isDoubled\":false,\"cards\":[{\"suit\":3,\"rank\":14,\"deckIndex\":0},{\"deckIndex\":3,\"rank\":10,\"suit\":2}]}]},{\"pendingBet\":20,\"seatID\":1,\"hands\":[]}],\"minBet\":10,\"maxBet\":500,\"yourActions\":[\"hit\",\"stand\",\"double\"],\"yourAdditionalStake\":50,\"dealerCards\":[{\"suit\":3,\"rank\":14,\"deckIndex\":0},null],\"currentHandID\":1,\"phase\":\"playerTurn\",\"currentSeatID\":0},\"game\":\"blackjack\",\"version\":12,\"isPrivate\":false}}}",
  "s.tablePoker": "{\"table\":{\"_0\":{\"poker\":{\"buttonSeatID\":1,\"handNumber\":3,\"pot\":120,\"currentSeatID\":0,\"isHandInProgress\":true,\"awards\":[{\"seatID\":1,\"amount\":120,\"potIndex\":0},{\"amount\":10,\"potIndex\":1,\"handName\":\"Flush\",\"seatID\":0}],\"community\":[{\"deckIndex\":0,\"rank\":14,\"suit\":3},{\"rank\":10,\"deckIndex\":3,\"suit\":2},{\"deckIndex\":0,\"rank\":2,\"suit\":0}],\"showdown\":[{\"seatID\":1,\"handName\":\"Paar\"}],\"players\":[{\"hasCards\":true,\"isSittingOut\":false,\"holeCards\":[{\"suit\":3,\"rank\":14,\"deckIndex\":0},{\"suit\":2,\"rank\":10,\"deckIndex\":3}],\"streetBet\":0,\"seatID\":0,\"stack\":980,\"hasFolded\":false,\"isAllIn\":false},{\"lastAction\":{\"streetTotal\":20,\"kind\":\"bet\"},\"isAllIn\":false,\"streetBet\":20,\"stack\":900,\"isSittingOut\":false,\"hasFolded\":false,\"seatID\":1,\"hasCards\":true}],\"bigBlind\":10,\"street\":1,\"smallBlind\":5,\"yourLegalActions\":{\"canRaise\":true,\"maxRaiseTo\":980,\"canCheck\":false,\"minRaiseTo\":40,\"callAmount\":20},\"currentBet\":20},\"isPrivate\":true,\"game\":\"poker\",\"version\":5,\"seats\":[{\"isConnected\":true,\"player\":{\"displayName\":\"Kim\",\"friendCode\":\"ABC234\",\"id\":\"P1\"},\"isBot\":false,\"seatID\":0},{\"seatID\":1,\"isConnected\":true,\"isBot\":true,\"player\":{\"friendCode\":\"\",\"id\":\"bot-1\",\"displayName\":\"Bot Ava\"},\"botStyle\":\"shark\"}],\"tableID\":\"T2\"}}}",
  "s.tableClosed": "{\"tableClosed\":{\"reason\":\"Tisch verlassen\"}}",
  "s.actionResultOK": "{\"actionResult\":{\"_0\":{\"accepted\":true,\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\"}}}",
  "s.actionResultNo": "{\"actionResult\":{\"_0\":{\"accepted\":false,\"actionID\":\"E621E1F8-C36C-495A-93FC-0C247A3E6E5F\",\"reason\":\"Spielstand veraltet\"}}}",
  "s.notice": "{\"notice\":{\"_0\":\"Hallo\"}}",
  "s.error": "{\"error\":{\"_0\":{\"code\":\"roomNotFound\",\"message\":\"Kein Raum\"}}}",
  "s.pong": "{\"pong\":{}}",
};

const sample = (k: string): string => {
  const s = SWIFT_SAMPLES[k];
  if (s === undefined) throw new Error(`missing sample ${k}`);
  return s;
};
const keys = (prefix: string) => Object.keys(SWIFT_SAMPLES).filter((k) => k.startsWith(prefix));

describe('protocol: round-trips against real Swift encoder output', () => {
  it.each(keys('c.'))('client message %s', (k) => {
    const decoded = decodeClientMessage(sample(k));
    expect(decoded).not.toBeNull();
    expect(JSON.parse(encodeClientMessage(decoded!))).toEqual(JSON.parse(sample(k)));
  });

  it.each(keys('s.'))('server message %s', (k) => {
    const decoded = decodeServerMessage(sample(k));
    expect(decoded).not.toBeNull();
    expect(JSON.parse(encodeServerMessage(decoded!))).toEqual(JSON.parse(sample(k)));
  });
});

describe('protocol: decoded values', () => {
  it('hello without token decodes to token null and encodes without the key', () => {
    const m = decodeClientMessage(sample('c.hello'));
    expect(m).toEqual({ type: 'hello', hello: { token: null, displayName: 'Kim', protocolVersion: 1 } });
    expect(encodeClientMessage(m!)).toBe('{"hello":{"_0":{"displayName":"Kim","protocolVersion":1}}}');
  });

  it('encodes every client message in the exact Swift shape', () => {
    const id = 'e621e1f8-c36c-495a-93fc-0c247a3e6e5f';
    const cases: [ClientMessage, string][] = [
      [{ type: 'ping' }, '{"ping":{}}'],
      [{ type: 'startRoom' }, '{"startRoom":{}}'],
      [{ type: 'rename', displayName: 'A' }, '{"rename":{"displayName":"A"}}'],
      [{ type: 'joinRoom', code: 'ABCDEF' }, '{"joinRoom":{"code":"ABCDEF"}}'],
      [{ type: 'findMatch', game: 'poker' }, '{"findMatch":{"game":"poker"}}'],
      [{ type: 'hello', hello: { token: 't', displayName: 'K', protocolVersion: 1 } }, '{"hello":{"_0":{"displayName":"K","protocolVersion":1,"token":"t"}}}'],
      [{ type: 'tableAction', request: { actionID: id, stateVersion: 3, action: { type: 'poker', action: { type: 'raise', to: 40 } } } },
        '{"tableAction":{"_0":{"actionID":"E621E1F8-C36C-495A-93FC-0C247A3E6E5F","stateVersion":3,"action":{"poker":{"action":{"raise":{"to":40}}}}}}}'],
      [{ type: 'tableAction', request: { actionID: id, stateVersion: 3, action: { type: 'blackjack', action: 'hit' } } },
        '{"tableAction":{"_0":{"actionID":"E621E1F8-C36C-495A-93FC-0C247A3E6E5F","stateVersion":3,"action":{"blackjack":{"action":"hit"}}}}}'],
      [{ type: 'tableAction', request: { actionID: id, stateVersion: 0, action: { type: 'placeBet', amount: 25 } } },
        '{"tableAction":{"_0":{"actionID":"E621E1F8-C36C-495A-93FC-0C247A3E6E5F","stateVersion":0,"action":{"placeBet":{"amount":25}}}}}'],
    ];
    for (const [m, json] of cases) expect(encodeClientMessage(m)).toBe(json);
  });

  it('blackjack snapshot: hidden dealer card, results, deadline', () => {
    const m = decodeServerMessage(sample('s.tableBJ'));
    if (m?.type !== 'table') throw new Error('expected table');
    const t = m.snapshot;
    expect(t.version).toBe(12);
    expect(t.turnDeadline).toBe(1700000025500);
    expect(t.poker).toBeNull();
    expect(t.seats[0]!.botStyle).toBeNull();
    expect(t.seats[1]!.botStyle).toBe('shark');
    expect(t.blackjack!.dealerCards).toEqual([{ rank: 14, suit: 3, deckIndex: 0 }, null]);
    expect(t.blackjack!.seats[0]!.pendingBet).toBeNull();
    expect(t.blackjack!.seats[0]!.hands[0]!.result).toEqual({ handID: 1, outcome: 'blackjack', stake: 50, payout: 125 });
    expect(t.blackjack!.yourActions).toEqual(['hit', 'stand', 'double']);
  });

  it('poker snapshot: street as int, redacted hole cards, awards', () => {
    const m = decodeServerMessage(sample('s.tablePoker'));
    if (m?.type !== 'table') throw new Error('expected table');
    const p = m.snapshot.poker!;
    expect(m.snapshot.yourSeatID).toBeNull();
    expect(m.snapshot.turnDeadline).toBeNull();
    expect(p.street).toBe(1);
    expect(p.players[1]!.holeCards).toBeNull();
    expect(p.players[1]!.lastAction).toEqual({ kind: 'bet', streetTotal: 20 });
    expect(p.awards[0]!.handName).toBeNull();
    expect(p.yourLegalActions?.minRaiseTo).toBe(40);
  });

  it('other server messages', () => {
    expect(decodeServerMessage(sample('s.roomNil'))).toEqual({ type: 'room', room: null });
    expect(decodeServerMessage(sample('s.mmSearching'))).toEqual({ type: 'matchmaking', status: { type: 'searching', game: 'poker', since: 1700000000123 } });
    expect(decodeServerMessage(sample('s.mmNoMatch'))).toEqual({ type: 'matchmaking', status: { type: 'noMatchFound', game: 'blackjack' } });
    expect(decodeServerMessage(sample('s.welcome'))).toMatchObject({ type: 'welcome', account: { token: 'secret', onlineChips: 5000 } });
    expect(decodeServerMessage(sample('s.account'))).toMatchObject({ type: 'account', account: { token: null } });
    expect(decodeServerMessage(sample('s.actionResultOK'))).toEqual({
      type: 'actionResult', result: { actionID: 'E621E1F8-C36C-495A-93FC-0C247A3E6E5F', accepted: true, reason: null },
    });
    expect(decodeServerMessage(sample('s.notice'))).toEqual({ type: 'notice', text: 'Hallo' });
    expect(decodeServerMessage(sample('s.error'))).toEqual({ type: 'error', error: { code: 'roomNotFound', message: 'Kein Raum' } });
    expect(decodeServerMessage(sample('s.pong'))).toEqual({ type: 'pong' });
  });

  it('accepts the alternative forms Swift also accepts (explicit null, lowercase UUID, extra keys)', () => {
    expect(decodeServerMessage('{"room":{"_0":null}}')).toEqual({ type: 'room', room: null });
    expect(decodeServerMessage('{"account":{"_0":{"player":{"id":"a","displayName":"b","friendCode":"c"},"onlineChips":1,"token":null}}}'))
      .toMatchObject({ type: 'account', account: { token: null } });
    expect(decodeServerMessage('{"actionResult":{"_0":{"actionID":"e621e1f8-c36c-495a-93fc-0c247a3e6e5f","accepted":true}}}'))
      .toMatchObject({ result: { actionID: 'E621E1F8-C36C-495A-93FC-0C247A3E6E5F' } });
    expect(decodeServerMessage('{"pong":{"extra":1}}')).toEqual({ type: 'pong' });
  });
});

describe('protocol: malformed input never throws', () => {
  const bad: unknown[] = [
    '', 'not json', 'null', '[]', '42', '"pong"', '{}',
    '{"pong":{},"ping":{}}',
    '{"pong":true}',
    '{"unknownCase":{}}',
    '{"notice":{"_0":5}}',
    '{"notice":{}}',
    '{"room":{"_0":{"code":"ABCDEF"}}}',
    '{"matchmaking":{"_0":{"searching":{"game":"roulette","since":1}}}}',
    '{"matchmaking":{"_0":{"bogus":{}}}}',
    '{"account":{"_0":{"player":{"id":"a","displayName":"b","friendCode":"c"},"onlineChips":1.5}}}',
    '{"error":{"_0":{"code":"teapot","message":"x"}}}',
    '{"actionResult":{"_0":{"actionID":"not-a-uuid","accepted":true}}}',
    '{"table":{"_0":{"tableID":"T","game":"poker","version":1,"isPrivate":false,"seats":[{"seatID":0}]}}}',
    '{"table":{"_0":{"tableID":"T","game":"blackjack","version":1,"isPrivate":false,"seats":[],"blackjack":{"phase":"betting","bettingOpen":true,"dealerCards":[{"rank":15,"suit":0,"deckIndex":0}],"seats":[],"minBet":1,"maxBet":2,"yourActions":[],"yourAdditionalStake":0}}}}',
    new ArrayBuffer(4), undefined, 7,
  ];
  it.each(bad.map((b, i) => [i, b] as const))('case %i is rejected', (_i, input) => {
    expect(() => decodeServerMessage(input)).not.toThrow();
    expect(decodeServerMessage(input)).toBeNull();
  });

  it('rejects oversize messages', () => {
    const big = `{"notice":{"_0":"${'x'.repeat(MAX_MESSAGE_BYTES)}"}}`;
    expect(decodeServerMessage(big)).toBeNull();
    const r = decodeServerMessageResult(big);
    expect(r.ok).toBe(false);
  });

  it('reports a path for errors', () => {
    const r = decodeServerMessageResult('{"notice":{"_0":5}}');
    expect(r).toEqual({ ok: false, error: '$.notice._0: expected string' });
  });

  it('rejects malformed client messages', () => {
    expect(decodeClientMessage('{"createRoom":{"game":"slots"}}')).toBeNull();
    expect(decodeClientMessage('{"tableAction":{"_0":{"actionID":"E621E1F8-C36C-495A-93FC-0C247A3E6E5F","stateVersion":1,"action":{"poker":{"action":{"raise":{}}}}}}}')).toBeNull();
  });
});
